# Combine FOUR figures together
setwd('/gpfs/gibbs/pi/zhao/jh2875/ps_PRS/review/PLOS_CB/simulation/organize_res')
library(ggplot2)
library(ggpubr)
library(grid)
library(gtable)
library(Cairo)

### PD-PRS
# stack
p1 <- readRDS('../simu_data_interaction/data/subgroup_stack.RDS')
p1.all <- ggarrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],
                    ncol=2,nrow=2,common.legend=T,legend='right')
# relachange
p2 <- readRDS('../simu_data_interaction/data/rela_chan_subgroup.RDS')

### Chasman
p3 <- readRDS('../chasman/data/analysis/inter_subgroup_stack.RDS')
p3.all <- ggarrange(p3[[1]],p3[[2]],p3[[3]],p3[[4]],
		    ncol=2,nrow=2,common.legend=T,legend='right')

p4 <- readRDS('../chasman/data/analysis/inter_rela_chan.RDS')

# Suppose composite1 and composite2 are generated by ggarrange:
grob1 <- ggplotGrob(p1.all)
grob2 <- ggplotGrob(p3.all)

# Identify the x-axis components; these are typically labeled "axis-b".
axis_index1 <- which(grob1$layout$name == "axis-b")
axis_index2 <- which(grob2$layout$name == "axis-b")

# Use unit.pmax to compute the maximum width between the two
if (length(axis_index1) > 0 && length(axis_index2) > 0) {
  max_width <- unit.pmax(grob1$widths[axis_index1], grob2$widths[axis_index2])

  # Set both to the maximum
  grob1$widths[axis_index1] <- max_width
  grob2$widths[axis_index2] <- max_width
}

CairoPNG('simulation_figure.png',
         bg='white',width=600*8,height=600*6,res=72*3)
ggarrange(p1.all,p2,p3.all,p4,nrow=2,ncol=2,labels = 'AUTO',align='hv')

dev.off()

